#!/usr/bin/env bash
# Export fresh AWS credentials into litellm/.env (for SSO / temporary ASIA keys).
# Usage: ./refresh-aws-env.sh [aws-profile-name]

set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$ROOT/.env"
PROFILE="${1:-${AWS_PROFILE:-default}}"

if ! command -v aws &>/dev/null; then
  echo "aws CLI is required."
  exit 1
fi

echo "Logging in / exporting credentials for profile: $PROFILE"
aws sso login --profile "$PROFILE" 2>/dev/null || true

CREDS="$(aws configure export-credentials --profile "$PROFILE" --format env)"
eval "$CREDS"

if [[ -z "${AWS_ACCESS_KEY_ID:-}" || -z "${AWS_SECRET_ACCESS_KEY:-}" ]]; then
  echo "Failed to export credentials for profile '$PROFILE'."
  exit 1
fi

REGION="${AWS_REGION:-${AWS_DEFAULT_REGION:-us-east-1}}"

cat > "$ENV_FILE" <<EOF
# Auto-generated by refresh-aws-env.sh — expires with your SSO/temporary session
AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN:-}
AWS_REGION_NAME=${REGION}
EOF

echo "Updated $ENV_FILE"
aws sts get-caller-identity --profile "$PROFILE" 2>/dev/null || aws sts get-caller-identity
