# Export fresh AWS credentials into litellm\.env (Windows / SSO / temporary ASIA keys).
# Usage: .\refresh-aws-env.ps1 [aws-profile-name]

param(
    [string]$Profile = $(if ($env:AWS_PROFILE) { $env:AWS_PROFILE } else { 'default' })
)

$ErrorActionPreference = 'Stop'
Set-Location $PSScriptRoot

$EnvFile = Join-Path $PSScriptRoot '.env'

if (-not (Get-Command aws -ErrorAction SilentlyContinue)) {
    Write-Host 'aws CLI is required.'
    exit 1
}

Write-Host "Logging in / exporting credentials for profile: $Profile"
aws sso login --profile $Profile 2>$null

$credLines = aws configure export-credentials --profile $Profile --format env 2>$null
if ($LASTEXITCODE -ne 0 -or -not $credLines) {
    Write-Host "Failed to export credentials for profile '$Profile'."
    exit 1
}

$creds = @{}
foreach ($line in $credLines) {
    if ($line -match '^export\s+(\w+)=(.+)$') {
        $creds[$Matches[1]] = $Matches[2].Trim('"')
    }
    elseif ($line -match '^(\w+)=(.+)$') {
        $creds[$Matches[1]] = $Matches[2].Trim('"')
    }
}

if (-not $creds['AWS_ACCESS_KEY_ID'] -or -not $creds['AWS_SECRET_ACCESS_KEY']) {
    Write-Host "Failed to parse credentials for profile '$Profile'."
    exit 1
}

$region = if ($creds['AWS_REGION']) { $creds['AWS_REGION'] }
          elseif ($creds['AWS_DEFAULT_REGION']) { $creds['AWS_DEFAULT_REGION'] }
          else { 'us-east-1' }

$sessionToken = if ($creds['AWS_SESSION_TOKEN']) { $creds['AWS_SESSION_TOKEN'] } else { '' }

@"
# Auto-generated by refresh-aws-env.ps1 — expires with your SSO/temporary session
AWS_ACCESS_KEY_ID=$($creds['AWS_ACCESS_KEY_ID'])
AWS_SECRET_ACCESS_KEY=$($creds['AWS_SECRET_ACCESS_KEY'])
AWS_SESSION_TOKEN=$sessionToken
AWS_REGION_NAME=$region
"@ | Set-Content -Path $EnvFile -Encoding utf8

Write-Host "Updated $EnvFile"
aws sts get-caller-identity --profile $Profile 2>$null
if ($LASTEXITCODE -ne 0) { aws sts get-caller-identity }
